{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-20T18:05:38Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: release 0.0.12
    sha: e2b81ef78e1cb695f5c9468f00b289940ed7016e
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: add variables
    sha: 0d329b6201cfe2b920fbad78d4d34673547cc1be
  - author:
      email: salaboy@gmail.com
      name: salaboy
    branch: master
    committer:
      email: salaboy@gmail.com
      name: salaboy
    message: |
      adding web security filters
    sha: 8b96128c893e99b0e0ef8542f359af5ff7d2cba7
  gitHttpUrl: https://github.com/salaboy/fmtok8s-email-rest
  gitOwner: salaboy
  gitRepository: fmtok8s-email-rest
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-email-rest/releases/tag/v0.0.13
  version: v0.0.13
status: {}
 
{{- end }}
