{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-05-24T08:42:25Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: release 0.0.20
    sha: 01690b5fd33f5231ac6f9be61f113f9cfc4e4c75
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: add variables
    sha: df8df099d488d47be09ed87ff333e51f3c5c4604
  - author:
      email: salaboy@gmail.com
      name: salaboy
    branch: master
    committer:
      email: salaboy@gmail.com
      name: salaboy
    message: |
      adding spring profiles
    sha: c062730aeadf921a7dcf218a6aad4beaf26c6b2f
  gitHttpUrl: https://github.com/salaboy/fmtok8s-email-rest
  gitOwner: salaboy
  gitRepository: fmtok8s-email-rest
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-email-rest/releases/tag/v0.0.21
  version: v0.0.21
status: {}
 
{{- end }}
