{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-21T00:18:18Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: release 0.0.13
    sha: 322020724bd60da9a8c1d54ccdf033dde16c8141
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: add variables
    sha: 1e3de42743287f8be4914bddf19b72e23b665c7c
  - author:
      email: salaboy@gmail.com
      name: salaboy
    branch: master
    committer:
      email: salaboy@gmail.com
      name: salaboy
    message: |
      adding security filters for actuator
    sha: 883637eaec093fb25b4ad3fb64a62352b6f06347
  gitHttpUrl: https://github.com/salaboy/fmtok8s-email-rest
  gitOwner: salaboy
  gitRepository: fmtok8s-email-rest
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-email-rest/releases/tag/v0.0.14
  version: v0.0.14
status: {}
 
{{- end }}
