{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-10T16:29:55Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: release 0.0.17
    sha: f96a6b8f17f6d547b671b0bcfab131df15e71660
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: add variables
    sha: 432db15ce40cdb821bc3177ae158f6e748f00428
  - author:
      email: salaboy@gmail.com
      name: salaboy
    branch: master
    committer:
      email: salaboy@gmail.com
      name: salaboy
    message: |
      updating deployment for servicemonitor and updating tracing config
    sha: c9636417f92f0ef08c6d8d5a0d23c2a409b7b862
  gitHttpUrl: https://github.com/salaboy/fmtok8s-email-rest
  gitOwner: salaboy
  gitRepository: fmtok8s-email-rest
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-email-rest/releases/tag/v0.0.18
  version: v0.0.18
status: {}
 
{{- end }}
